[workspace]
authors = ["codechenx <codechenx@gmail.com>"]
channels = ["conda-forge"]
name = "FastTableViewer"
platforms = ["osx-arm64"]
version = "0.9.2"

[tasks]

[dependencies]
go = ">=1.25.4,<2"
asciinema = ">=2.4.0,<3"
